spring:
  application:
    name: BaiduYunParsing
  profiles:
    active: dev

baidu:
  # TODO 填入参数
  bduss:
  uid:
  stoken:
  # Fixed Param
  dev-uid: 533380000000044
  cuid: 6B80B835960CE6CF54A8DA27469C5A23|533380000000044