spring:
  application:
    name: BaiduYunParsing
  profiles:
    active: dev

baidu:
  bduss: dRN001dEdxV0kzaER3LUw0MU5TaUNQaXdBRHMyflFOTGw1YWY1R0VabDhxZGhmSVFBQUFBJCQAAAAAAAAAAAEAAACvXhMWYTE0Nzc2NTg5NzMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwcsV98HLFfbT
  uid: 370368175
  stoken: 794cc99bdcdb527821e37e3bb20b4c80ed5fc154b1b8853cb294519643d038fa
  # Fixed Param
  dev-uid: 533380000000044
  cuid: 6B80B835960CE6CF54A8DA27469C5A23|533380000000044