spring:
  application:
    name: BaiduYunParsing

baidu:
  bduss: kdMY3FMSTdVNFFpNzZRR0tyTkdsTmVNdURDQjQ0T0tCR2VHVEtOeEEzeHl0dGxmRUFBQUFBJCQAAAAAAAAAAAEAAACKx02x1~PU2szs0KsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHIpsl9yKbJfM
  uid: 2974664586
  stoken: 3d1d1580be2514cdf45df219b55a9e6d7527960bcfc1460b553841055c39b880
  # Fixed Param
  dev-uid: 282920757697800
  cuid: F0B702BAB09ED44EAF70820CCCED1F94|4VRJRMEYV